TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = (58, 66)
SLATE_SIZE = SLATE_WIDTH, SLATE_HEIGHT = (TILE_WIDTH, TILE_HEIGHT // 2)
WALL_SIZE = WALL_WIDTH, WALL_HEIGHT = (TILE_WIDTH // 2, TILE_HEIGHT - SLATE_HEIGHT // 2)

__all__ = [
    "TILE_SIZE",
    "TILE_WIDTH",
    "TILE_HEIGHT",
    "SLATE_SIZE",
    "SLATE_WIDTH",
    "SLATE_HEIGHT",
    "WALL_SIZE",
    "WALL_WIDTH",
    "WALL_HEIGHT",
]
