TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = (57, 65)
SLATE_SIZE = SLATE_WIDTH, SLATE_HEIGHT = (57, 33)
WALL_SIZE = WALL_WIDTH, WALL_HEIGHT = (29, 49)

__all__ = [
    "TILE_SIZE",
    "TILE_WIDTH",
    "TILE_HEIGHT",
    "SLATE_SIZE",
    "SLATE_WIDTH",
    "SLATE_HEIGHT",
    "WALL_SIZE",
    "WALL_WIDTH",
    "WALL_HEIGHT",
]
