TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = (56, 64)
SLATE_SIZE = SLATE_WIDTH, SLATE_HEIGHT = (57, 33)
WALL_SIZE = WALL_WIDTH, WALL_HEIGHT = (29, 49)
RENDER_OFFSET = 3
SIGHT_LIMIT = 100
Z_LIMIT = 30

__all__ = [
    "TILE_SIZE",
    "TILE_WIDTH",
    "TILE_HEIGHT",
    "RENDER_OFFSET",
    "SIGHT_LIMIT",
    "SLATE_SIZE",
    "SLATE_WIDTH",
    "SLATE_HEIGHT",
    "WALL_SIZE",
    "WALL_WIDTH",
    "WALL_HEIGHT",
    "Z_LIMIT",
]
